apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
      version: blue
  template:
    metadata:
      labels:
        app: portfolio
        version: blue
    spec:
      containers:
      - name: portfolio
        image: ppt1001/portfolio:blue # Adjust the image tag for the blue version
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"