apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
      version: green
  template:
    metadata:
      labels:
        app: portfolio
        version: green
    spec:
      containers:
      - name: portfolio
        image: ppt1001/portfolio:green # Adjust the image tag for the green version
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"