apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
      version: blue
  template:
    metadata:
      labels:
        app: portfolio
        version: blue
    spec:
      containers:
      - name: portfolio
        image: ppt1001/portfolio:blue # Adjust the image tag for the blue version
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"