---
- name: Add NodeSource repository
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
  args:
    warn: false

- name: Install Node.js and npm
  apt:
    name: nodejs
    state: present
    update_cache: yes
  become: true

- name: Verify Node.js installation
  command: node --version
  register: node_version
  changed_when: false

- name: Verify npm installation
  command: npm --version
  register: npm_version
  changed_when: false

- name: Display versions
  debug:
    msg: "Node.js version: {{ node_version.stdout }}, npm version: {{ npm_version.stdout }}"